### ISSUE TITLE
Beginners help

### ISSUE THREAD

**Issue by wernerlaude** [myrho/elm-round#3]
Thanks for your work..
It would be helpful for a beginner(like me) if you also tell how to import it
ex. -> import Html.Attributes exposing (..)
Thanks

**Comment by myrho** [comment]
Hi! Thank you for your feedback. Would [this note](https://github.com/myrho/elm-round/commit/088d20407f830fc726377bb786b8d0d98143b6d5) help beginners in your view?

**Comment by myrho** [comment]
[Approved](https://github.com/myrho/elm-round/commit/088d20407f830fc726377bb786b8d0d98143b6d5#commitcomment-23407837)
