### ISSUE TITLE
doesn't work for large floats (scientific notation)

### ISSUE THREAD

**Issue by 2mol** [myrho/elm-round#6]
As soon as numbers reach the size where scientific notation is used, this library won't produce the right number of digits.

Minimal example, reproduce in elm-epl:

```elm
import Round
n = 7.34767309e22

Round.round 2 n
```

This gives `"7.34767309e+22.00" : String` instead of the expected `7.34e22`.

Also affects cuducos/elm-format-number#16

Edit:

While we're at it, there is also no handling of `Infinity` and `NaN`, both valid values of the `Float` type.

```elm
> Round.round 2 (1/0)
"Infinity.00" : String
> Round.round 2 (0/0)
"NaN.00" : String
>
```

**Comment by myrho** [comment]
Should be fixed now! Check out version 1.0.3.

**Comment by 2mol** [comment]
Awesome, that was very fast!

I see from the tests that `round 2 1.234e4` will format to `"12340.00"`. That's of course a correct interpretation of `round 2`. However if you ever happen to provide a variation that formats to `"1.23e4"`, that would be very useful. But that's just me looking a gift horse in the mouth, so thanks for making this library and for making it better!

PS: I can't send a PR against your repo website (on top of the github page), but it should be http://package.elm-lang.org/packages/myrho/elm-round/latest/, not http://package.elm-lang.org/packages/myrho/elm-round/1.0.0

**Comment by myrho** [comment]
Yes, I did something bad and rewrote the master history. There was just the 0.19 upgrade already merged in. I think that's the problem why you can't make a PR?

Would an inverse function of `toDecimal`, eg. `toScientific`, help you?

**Comment by 2mol** [comment]
Yes, having something like `toScientific` would be really cool.


No, I meant that the link to the docs displayed on top of the repo is something you configure in the repo settings, not something I can send a PR for:
![screen shot 2018-07-12 at 11 52 28](https://user-images.githubusercontent.com/1773075/42626253-1728f108-85ca-11e8-8aca-72d46acfef0e.png)

**Comment by myrho** [comment]
Oh, yes, thanks for pointing this out!
