### ISSUE TITLE
Merge with elm-format-number

### ISSUE THREAD

**Issue by janwirth** [myrho/elm-round#8]
https://package.elm-lang.org/packages/cuducos/elm-format-number/latest/

Both packages do `Float -> String` with different sets of options. Does it make sense to merge this?

**Comment by myrho** [comment]
Good point!

Any suggestions on how to merge the APIs?

**Comment by janwirth** [comment]
Add this package as roundingStrategy to elm-format-number locales.

**Comment by myrho** [comment]
Sounds reasonable! So it's an issue for elm-format-number, right?

Am 15. Juli 2019 14:58:01 MESZ schrieb Jan Wirth <notifications@github.com>:
>Add this package as roundingStrategy to elm-format-number locales.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/myrho/elm-round/issues/8#issuecomment-511391194

--
