### ISSUE TITLE
Round without converting to string

### ISSUE THREAD

**Issue by janwirth** [myrho/elm-round#9]
Sometimes I just want to reduce precision. It would be cool to be able to do this:
```elm
x = 213.14
round -1 x -- 210 : Float
```

**Comment by myrho** [comment]
I think `roundNum` does exactly that!

Am 15. Juli 2019 18:31:21 MESZ schrieb Jan Wirth <notifications@github.com>:
>Sometimes I just want to reduce precision. It would be cool to be able
>to do this:
>```elm
>round 2 0.12345 --> 0.12 : Float
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/myrho/elm-round/issues/9

--

**Comment by janwirth** [comment]
🤦‍♂
